- jsonobject/base_properties.py
this removes about 6,000 function declarations from `./manage.py runserver` on commcarehq
> don't create validation functions on instantiation

- jsonobject/containers.py
- test/tests.py
This resolves  http://manage.dimagi.com/default.asp?161566#895533
> Add __setitem__ for json array objects

- .travis.yml
- jsonobject/api.py
- jsonobject/base.py
- jsonobject/base_properties.py
- jsonobject/properties.py
- jsonobject/utils.py
- setup.py
- test/couchdbkit/couchdbkit.py
- test/test_stringconversions.py
- test/tests.py
- tox.ini
This will add some fixes to support both python3.4 and python2.7, the tests are passing and i have been using it so far without bugs.
Maybe launch it in a new major release?
thanks
> Add Python3 support

- jsonobject/base.py
@dannyroberts  Just came across this.
> Match string to format args

- jsonobject/utils.py
@dannyroberts i find my self modifying the base library for this so i thought i'd PR the change
cc: @esoergel
> Improve error message

- .travis.yml
- README.md
The link to 0.6.5.5 threw me off.
@dannyroberts cc: @calellowitz
> link to latest couchdbkit release

- setup.py
> Version 0.8.0

- .travis.yml
- .travis/install_cython.sh
- .travis/test_cython_files.sh
- README.md
- jsonobject/base.c
- jsonobject/base.pyx
- jsonobject/base_properties.c
- jsonobject/base_properties.pyx
- jsonobject/properties.c
- jsonobject/properties.pyx
- setup.py
- test/tests.py
- test_cython_files.sh
Should fix issue raised by @snopoke's comment here: https://github.com/dimagi/commcare-cloud/pull/1655#issue-183974672
> allow nested containers

- jsonobject/base.c
- jsonobject/base.pyx
- setup.py
> fix 'RuntimeError: dictionary changed size during iteration'

- setup.py
Already released, but I should have at least waited for tests.
> Bump version to 0.9.5

- jsonobject/containers.c
- jsonobject/containers.pyx
- setup.py
Don't overwrite the argument ```wrapped``` with an empty list.
>  fix JsonArray.__setitem__

- jsonobject/containers.c
- jsonobject/containers.pyx
- setup.py
- test/tests.py
Followup to https://github.com/dimagi/jsonobject/pull/157
🐡
> Fix JsonArray.__setitem__ with slice

- .travis.yml
> add Python 3.7 to travis tests

- setup.py
https://github.com/dimagi/jsonobject/issues/178
this look right to you @dannyroberts ?
anything else to do, or I can just publish to pypi once reviewed/merged?
> 0.9.10 release

- CHANGES.md
- setup.py
> Bump version to 2.0.0

- CHANGES.md
- setup.py
and document changes.
(Finally getting around to this!)
> Bump version to 2.1.0

- LIFECYCLE.md
- README.md
Jotting down some of the unwritten processes we use to maintain this codebase and package.
Before merging I'll run through the instructions myself to release the latest version, and make any updates as needed.
> Add LIFECYCLE.md to describe the maintenance and release process

- .github/workflows/tests.yml
- setup.py
- test/test_stringconversions.py
- tox.ini
Recreating https://github.com/dimagi/jsonobject/pull/219 for the build to pass.
> [Recreated] Add support for Python 3.12

- CHANGES.md
- setup.py
> Bump version to 2.2.0

- version.py
Also add support for older Pythons where `datetime.UTC` is not available.
Tested version `check` and `update` locally on Python 3.9 and 3.13.
> Do not import jsonobject in version.py
